//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string accountNumber { get; set; }
        public decimal balance { get; set; }
        public int bonus { get; set; }
        public int accountHolder { get; set; }
        public int accountType { get; set; }
    
        public virtual AccountHolder AccountHolder1 { get; set; }
        public virtual AccountType AccountType1 { get; set; }
    }
}
