//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionWinner
    {
        public int id { get; set; }
        public int idCompetition { get; set; }
        public System.DateTime finalDate { get; set; }
        public int idWinner { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual FootballClub FootballClub { get; set; }
    }
}
