//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballClub
    {
        public FootballClub()
        {
            this.CompetitionWinners = new HashSet<CompetitionWinner>();
            this.Players = new HashSet<Player>();
            this.TransfersHistories = new HashSet<TransfersHistory>();
            this.TransfersHistories1 = new HashSet<TransfersHistory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string stadium { get; set; }
        public System.DateTime foundation { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<CompetitionWinner> CompetitionWinners { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<TransfersHistory> TransfersHistories { get; set; }
        public virtual ICollection<TransfersHistory> TransfersHistories1 { get; set; }
    }
}
