//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infirmary
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string position { get; set; }
        public System.DateTime dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public string description { get; set; }
    }
}
