//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FootballEntities : DbContext
    {
        public FootballEntities()
            : base("name=FootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionWinner> CompetitionWinners { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FootballClub> FootballClubs { get; set; }
        public virtual DbSet<InjuryHistory> InjuryHistories { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<TransfersHistory> TransfersHistories { get; set; }
        public virtual DbSet<Infirmary> Infirmaries { get; set; }
    
        [DbFunction("FootballEntities", "fn_footballTeam")]
        public virtual IQueryable<fn_footballTeam_Result> fn_footballTeam(string team)
        {
            var teamParameter = team != null ?
                new ObjectParameter("team", team) :
                new ObjectParameter("team", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_footballTeam_Result>("[FootballEntities].[fn_footballTeam](@team)", teamParameter);
        }
    }
}
