//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.InjuryHistories = new HashSet<InjuryHistory>();
            this.TransfersHistories = new HashSet<TransfersHistory>();
        }
    
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime born { get; set; }
        public string position { get; set; }
        public int idCountry { get; set; }
        public Nullable<int> idClub { get; set; }
        public string img { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual FootballClub FootballClub { get; set; }
        public virtual ICollection<InjuryHistory> InjuryHistories { get; set; }
        public virtual ICollection<TransfersHistory> TransfersHistories { get; set; }
    }
}
