//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT
{
    using System;
    
    public enum PaymentResult : int
    {
        OK = 0,
        InvalidAccount = 1,
        NotEnoughFunds = 2,
        UnknownError = 3
    }
}
